# Generated by Django 3.1.5 on 2021-01-19 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210119_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='listing',
            field=models.ManyToManyField(related_name='comments', to='auctions.Listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.ManyToManyField(related_name='listedBids', to=settings.AUTH_USER_MODEL),
        ),
    ]
