# Generated by Django 3.1.5 on 2021-01-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('listing', models.ManyToManyField(null=True, related_name='listings', to='auctions.Listing')),
            ],
        ),
    ]
